### ISSUE TITLE
Please remove the logging

### ISSUE THREAD

**Issue by marmelad52** [Madhan-Rkv-10/adaptive_sizer#1]
Please remove these lines in the code, or add the option to prohibit logging:
`log("Source Device   width $width and Height $height");`
`log("setup height $height");`

The console is very clogged, so it is impossible to find the necessary information

**Comment by Madhan-Rkv-10** [comment]
Issue resolved: disabled  logging for device dimensions and setup height. Logging is now disabled by default to keep the console uncluttered. Closing this issue
